name: sharkwatch
region: fra
services:
  - name: web
    dockerfile_path: Dockerfile
    github:
      repo: <will-be-set-manually>
      branch: main
      deploy_on_push: true
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /
    envs:
      - key: DB_HOST
        value: encrypted-api-production.cplplylv4i5w.eu-central-1.rds.amazonaws.com
        scope: RUN_TIME
      - key: DB_PORT
        value: "5432"
        scope: RUN_TIME
      - key: DB_NAME
        value: sharks
        scope: RUN_TIME
      - key: DB_USER
        value: dbmaster
        scope: RUN_TIME
      - key: DB_PASSWORD
        value: rrfPMUriOKtsBkweJm21
        scope: RUN_TIME
        type: SECRET
      - key: PORT
        value: "3000"
        scope: RUN_TIME
